name: Test

on:
  push:
  pull_request:

jobs:
  test-appconfig-script:
    name: Test app-config generation script
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: pip
      - name: Install Python requirements
        run: pip install -r requirements.txt
      - name: Generate test template
        run: |
          pip freeze
          ./template_app_config_local.sh --verbosity 9 --accept_defaults -ARGOCD_SERVER localhost:9999 \
            -BACKSTAGE_AUTH_SECRET SOME_BS_AUTH_SECRET -GITHUB_PERSONAL_ACCESS_TOKEN SOME_GH_PAT \
            -ARGOCD_AUTH_TOKEN SOME_ARGOCD_AUTH_TOKEN -ARGOCD_ADMIN_PASSWORD SOME_ADMIN_PW -SERVICE_ACCOUNT_TOKEN SOME_SAT
      - name: Check with default
        run: |
          diff app-config.local.yaml .github/test/app-config.test.yaml
